// TODO: apagar este db quando a api estiver pronta

export const users = [
  {
      id: 1,
      name: "Ana Silva",
      email: "ana12@gmail.com",
      password: "1234g",
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
  },
  {
      id: 2,
      name: "Lucas M. Oliveira",
      email: "alucas@gmail.com",
      password: "124g@",
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
  },
  {
      id: 3,
      name: "Silveira Barbosa",
      email: "sb_87@gmail.com",
      password: "senha12",
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
  },
];

export const transactions = [
    {
        id: 1,
        type: "Entrada",
        value: 329.98,
        category: "Comércio",
        description: "Lucro de terça-feira na venda de roupas",
        userId: 2,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
    {
        id: 2,
        type: "Saída",
        value: 42,
        description: "Descrição aqui",
        category: "Compras",
        userId: 1,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
    {
        id: 3,
        type: "Entrada",
        value: 329.98,
        category: "Outro",
        description:
            "Lucro de terça-feira na venda de comida, etc etc, descrição aqui ... ...",
        userId: 2,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
    {
        id: 4,
        type: "Entrada",
        value: 42,
        category: "Compras",
        description: '',
        userId: 3,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
    {
        id: 5,
        type: "Entrada",
        value: 329.98,
        category: "Outro",
        description: "Lucro de terça-feira na venda de roupas",
        userId: 1,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
    {
        id: 6,
        type: "Saída",
        value: 42,
        category: "Compras",
        description: '',
        userId: 3,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
    {
        id: 7,
        type: "Entrada",
        value: 42,
        category: "Investimento",
        description: '',
        userId: 2,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
    {
        id: 8,
        type: "Saída",
        value: 42,
        category: "Outro",
        description: 'Descrição aqui etc etc etc etc jajajajaj sssss dddd. etc etc descrção grande aqui Descrição aqui etc etc etc etc jajajajaj sssss dddd. etc etc descrção grande aqui',
        userId: 1,
        createdAt: new Date(Date.now()),
        updatedAt: new Date(Date.now()),
    },
];


