export const transactions = [
      {
        id: "01",
        type: "Entrada",
        value: 329.98,
        category: "Comércio",
        description: "Lucro de terça-feira na venda de roupas",
        createdAt: "09/12/2021",
      },
      {
        id: "02",
        type: "Saída",
        value: 42,
        description: "Descrição aqui",
        category: "Compras",
        createdAt: "09/12/2021",
      },
      {
        id: "03",
        type: "Entrada",
        value: 329.98,
        category: "Outro",
        description: "Lucro de terça-feira na venda de comida, etc etc, descrição aqui ... ...",
        createdAt: "09/12/2021",
      },
      {
        id: "04",
        type: "Entrada",
        value: 42,
        category: "Compras",
        createdAt: "09/12/2021",
      },
      {
        id: "05",
        type: "Entrada",
        value: 329.98,
        category: "Outro",
        description: "Lucro de terça-feira na venda de roupas",
        createdAt: "09/12/2021",
      },
      {
        id: "06",
        type: "Saída",
        value: 42,
        category: "Compras",
        createdAt: "09/12/2021",
      },
      {
        id: "07",
        type: "Entrada",
        value: 42,
        category: "Investimento",
        createdAt: "09/12/2021",
      },
      {
        id: "08",
        type: "Saída",
        value: 42,
        category: "Compras",
        createdAt: "09/12/2021",
      },
]